### ISSUE TITLE
Appointment-table: Backend: Hide days in the past for users oder admins

### ISSUE THREAD

**Issue by Theophilix** [Theophilix/event-table-edit#189]
Normally days in the past are shown. But this is unnecessary. We have to add an option to the backend "Hide old dates for users" and "Hide old dates for admin".
If these options are checked, the user oder the admin won't see the dates < than today.

**Comment by lindamotte** [comment]
Hello, first of all I would like to thank you for your good work! I use the appointment table for a billiard club to book time at the billiard table. In times of the corona pandemic, only 12 people are allowed to stay in the sports facility. At the moment I always have to delete the previous rows so that the overview is better on the mobile phone. that involves a lot of manual work, i'm looking forward to the expansion and would like to donate some money now, where can i do that? Kindest regards Linda, from Germany
